name: generate-snake-game-from-github-contribution-grid
uses: Platane/snk/svg-only@v3
  with:
    github_user_name: CGuillotG

    outputs: |
      dist/github-snake.svg
      dist/github-snake-dark.svg?palette=github-dark